import { DocTemplate } from '@/types/document';

const gen = () => Math.random().toString(36).substring(2, 9);
const cell = (content: string, bold = false, bg = '') => ({ id: gen(), content, bold, bg });
const row = (...cells: ReturnType<typeof cell>[]) => ({ id: gen(), cells });
const item = (text: string) => ({ id: gen(), text });

export const DOC_TEMPLATES: DocTemplate[] = [
  // ─── DOCUMENTS ───────────────────────────────────────────────────────────────
  {
    id: 'payment-receipt',
    name: 'Квитанция об оплате',
    description: 'Официальный документ подтверждения платежа с подписью',
    category: 'Документы',
    icon: '🧾',
    doc: {
      title: 'КВИТАНЦИЯ ОБ ОПЛАТЕ',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading1', content: 'КВИТАНЦИЯ ОБ ОПЛАТЕ', align: 'center' },
        { id: gen(), type: 'table', rows: [
          row(cell('Дата:', true), cell('________________')),
          row(cell('Счёт №:', true), cell('________________')),
          row(cell('Получено от:', true), cell('________________')),
          row(cell('Основание:', true), cell('________________')),
          row(cell('Сумма цифрами:', true), cell('________________')),
          row(cell('Сумма прописью:', true), cell('________________')),
        ], cols: 2 },
        { id: gen(), type: 'divider' },
        { id: gen(), type: 'table', rows: [
          row(cell('Принял:', true), cell('________________'), cell('Подпись плательщика:', true), cell('________________')),
        ], cols: 4 },
        { id: gen(), type: 'signature', content: 'Подпись кассира' },
      ],
    },
  },
  {
    id: 'contract',
    name: 'Договор услуг',
    description: 'Стандартный договор оказания услуг с реквизитами сторон',
    category: 'Документы',
    icon: '📝',
    doc: {
      title: 'Договор оказания услуг',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ДОГОВОР ОКАЗАНИЯ УСЛУГ №___', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'г. ________________    «___» ____________ 20___ г.' },
        { id: gen(), type: 'paragraph', content: '______________________ (далее «Исполнитель»), именуемый(ая) в дальнейшем Исполнитель, с одной стороны, и ______________________ (далее «Заказчик»), с другой стороны, заключили настоящий Договор о нижеследующем:' },
        { id: gen(), type: 'heading2', content: '1. ПРЕДМЕТ ДОГОВОРА' },
        { id: gen(), type: 'paragraph', content: '1.1. Исполнитель обязуется оказать Заказчику следующие услуги: __________________________.' },
        { id: gen(), type: 'paragraph', content: '1.2. Срок оказания услуг: с «___» _______ 20__ по «___» _______ 20__.' },
        { id: gen(), type: 'heading2', content: '2. СТОИМОСТЬ И ПОРЯДОК ОПЛАТЫ' },
        { id: gen(), type: 'paragraph', content: '2.1. Стоимость услуг составляет: _______ руб. (__________________________).' },
        { id: gen(), type: 'heading2', content: '3. РЕКВИЗИТЫ И ПОДПИСИ СТОРОН' },
        { id: gen(), type: 'table', rows: [
          row(cell('ИСПОЛНИТЕЛЬ', true), cell('ЗАКАЗЧИК', true)),
          row(cell('ФИО: __________________'), cell('ФИО: __________________')),
          row(cell('Адрес: __________________'), cell('Адрес: __________________')),
          row(cell('Тел: __________________'), cell('Тел: __________________')),
          row(cell('Подпись: __________________'), cell('Подпись: __________________')),
        ], cols: 2 },
      ],
    },
  },
  {
    id: 'act-of-work',
    name: 'Акт выполненных работ',
    description: 'Двусторонний акт приёмки выполненных работ',
    category: 'Документы',
    icon: '✅',
    doc: {
      title: 'Акт выполненных работ',
      blocks: [
        { id: gen(), type: 'heading1', content: 'АКТ ВЫПОЛНЕННЫХ РАБОТ №___', align: 'center' },
        { id: gen(), type: 'paragraph', content: '«___» ____________ 20___ г.                                    г. ________________' },
        { id: gen(), type: 'paragraph', content: 'Мы, нижеподписавшиеся, составили настоящий акт о том, что Исполнитель выполнил, а Заказчик принял следующие работы:' },
        { id: gen(), type: 'table', rows: [
          row(cell('№', true), cell('Наименование работ', true), cell('Ед.изм.', true), cell('Кол-во', true), cell('Цена', true), cell('Сумма', true)),
          row(cell('1'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('2'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('3'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell(''), cell('ИТОГО:', true), cell(''), cell(''), cell(''), cell('')),
        ], cols: 6 },
        { id: gen(), type: 'paragraph', content: 'Работы выполнены в полном объёме, в установленные сроки, в надлежащем качестве. Стороны претензий не имеют.' },
        { id: gen(), type: 'table', rows: [
          row(cell('Сдал (Исполнитель)', true), cell('Принял (Заказчик)', true)),
          row(cell('__________________'), cell('__________________')),
        ], cols: 2 },
      ],
    },
  },
  {
    id: 'invoice',
    name: 'Счёт-фактура',
    description: 'Счёт на оплату товаров и услуг',
    category: 'Документы',
    icon: '🧮',
    doc: {
      title: 'Счёт-фактура',
      blocks: [
        { id: gen(), type: 'heading1', content: 'СЧЁТ-ФАКТУРА №___', align: 'center' },
        { id: gen(), type: 'table', rows: [
          row(cell('Поставщик:', true), cell('________________'), cell('Покупатель:', true), cell('________________')),
          row(cell('ИНН:', true), cell('________________'), cell('ИНН:', true), cell('________________')),
          row(cell('Адрес:', true), cell('________________'), cell('Адрес:', true), cell('________________')),
        ], cols: 4 },
        { id: gen(), type: 'table', rows: [
          row(cell('№', true, '#f0f0f0'), cell('Наименование', true, '#f0f0f0'), cell('Кол-во', true, '#f0f0f0'), cell('Цена', true, '#f0f0f0'), cell('НДС %', true, '#f0f0f0'), cell('Сумма', true, '#f0f0f0')),
          row(cell('1'), cell(''), cell(''), cell(''), cell('20%'), cell('')),
          row(cell('2'), cell(''), cell(''), cell(''), cell('20%'), cell('')),
          row(cell(''), cell('Итого без НДС:'), cell(''), cell(''), cell(''), cell('')),
          row(cell(''), cell('НДС:'), cell(''), cell(''), cell(''), cell('')),
          row(cell(''), cell('Итого с НДС:', true), cell(''), cell(''), cell(''), cell('')),
        ], cols: 6 },
      ],
    },
  },
  {
    id: 'letter',
    name: 'Деловое письмо',
    description: 'Официальное деловое письмо с реквизитами',
    category: 'Документы',
    icon: '✉️',
    doc: {
      title: 'Деловое письмо',
      blocks: [
        { id: gen(), type: 'paragraph', content: 'Кому: ______________________________', align: 'right' },
        { id: gen(), type: 'paragraph', content: 'От: ________________________________', align: 'right' },
        { id: gen(), type: 'paragraph', content: 'Дата: ______________________________', align: 'right' },
        { id: gen(), type: 'divider' },
        { id: gen(), type: 'heading2', content: 'Тема: ______________________________', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Уважаемый(ая) ______________________!' },
        { id: gen(), type: 'paragraph', content: 'Настоящим уведомляем Вас о том, что ___________________________________________.' },
        { id: gen(), type: 'paragraph', content: 'В связи с вышеизложенным просим Вас ___________________________________________.' },
        { id: gen(), type: 'paragraph', content: 'Надеемся на дальнейшее взаимовыгодное сотрудничество.' },
        { id: gen(), type: 'paragraph', content: 'С уважением,' },
        { id: gen(), type: 'paragraph', content: '____________________    ____________________' },
        { id: gen(), type: 'paragraph', content: '(подпись)              (расшифровка)' },
      ],
    },
  },
  {
    id: 'power-of-attorney',
    name: 'Доверенность',
    description: 'Нотариальная доверенность на представление интересов',
    category: 'Документы',
    icon: '🔏',
    doc: {
      title: 'Доверенность',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ДОВЕРЕННОСТЬ', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'г. ________________    «___» ____________ 20___ г.' },
        { id: gen(), type: 'paragraph', content: 'Я, ______________________, паспорт серия ___ № _______, выдан ________________, проживающий(ая) по адресу: ______________________, настоящей доверенностью уполномочиваю' },
        { id: gen(), type: 'paragraph', content: '______________________, паспорт серия ___ № _______, выдан ________________,' },
        { id: gen(), type: 'paragraph', content: 'представлять мои интересы в ____________________________________________ по вопросам ____________________________________________.' },
        { id: gen(), type: 'paragraph', content: 'Доверенность выдана сроком на _______ без права передоверия.' },
        { id: gen(), type: 'table', rows: [
          row(cell('Доверитель:', true), cell('___________________'), cell('Подпись:', true), cell('___________________')),
        ], cols: 4 },
      ],
    },
  },
  // ─── FORMS ───────────────────────────────────────────────────────────────────
  {
    id: 'application-form',
    name: 'Заявка / Анкета',
    description: 'Универсальная анкета для сбора данных',
    category: 'Формы',
    icon: '📋',
    doc: {
      title: 'Анкета',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading2', content: 'Личные данные', align: 'center' },
        { id: gen(), type: 'field', fieldLabel: 'Фамилия Имя Отчество', fieldOptions: { type: 'text', placeholder: 'Введите ФИО', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Дата рождения', fieldOptions: { type: 'date', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Email', fieldOptions: { type: 'email', placeholder: 'email@example.com', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Телефон', fieldOptions: { type: 'text', placeholder: '+7 (___) ___-__-__' } },
        { id: gen(), type: 'heading2', content: 'Дополнительная информация' },
        { id: gen(), type: 'field', fieldLabel: 'Комментарий', fieldOptions: { type: 'textarea', placeholder: 'Ваш комментарий...' } },
        { id: gen(), type: 'signature', content: 'Подпись заявителя' },
      ],
    },
  },
  {
    id: 'feedback-form',
    name: 'Форма обратной связи',
    description: 'Сбор отзывов и предложений',
    category: 'Формы',
    icon: '💬',
    doc: {
      title: 'Форма обратной связи',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading1', content: 'Оставьте отзыв', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Ваше мнение очень важно для нас!', align: 'center' },
        { id: gen(), type: 'field', fieldLabel: 'Имя', fieldOptions: { type: 'text', placeholder: 'Ваше имя' } },
        { id: gen(), type: 'field', fieldLabel: 'Email для ответа', fieldOptions: { type: 'email', placeholder: 'email@example.com' } },
        { id: gen(), type: 'field', fieldLabel: 'Тема обращения', fieldOptions: { type: 'select', options: ['Предложение', 'Жалоба', 'Вопрос', 'Благодарность'] } },
        { id: gen(), type: 'field', fieldLabel: 'Ваше сообщение', fieldOptions: { type: 'textarea', placeholder: 'Опишите вашу ситуацию...', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Оценка', fieldOptions: { type: 'select', options: ['⭐', '⭐⭐', '⭐⭐⭐', '⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'] } },
      ],
    },
  },
  {
    id: 'order-form',
    name: 'Форма заказа',
    description: 'Приём заказов на товары или услуги',
    category: 'Формы',
    icon: '🛒',
    doc: {
      title: 'Форма заказа',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading1', content: 'Оформление заказа', align: 'center' },
        { id: gen(), type: 'field', fieldLabel: 'Наименование товара/услуги', fieldOptions: { type: 'text', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Количество', fieldOptions: { type: 'number' } },
        { id: gen(), type: 'field', fieldLabel: 'Способ доставки', fieldOptions: { type: 'select', options: ['Самовывоз', 'Курьер', 'Почта', 'ТК'] } },
        { id: gen(), type: 'field', fieldLabel: 'Адрес доставки', fieldOptions: { type: 'textarea', placeholder: 'Город, улица, дом, квартира' } },
        { id: gen(), type: 'field', fieldLabel: 'Контактный телефон', fieldOptions: { type: 'text', placeholder: '+7 (___) ___-__-__', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Комментарий к заказу', fieldOptions: { type: 'textarea' } },
      ],
    },
  },
  {
    id: 'medical-form',
    name: 'Медицинская анкета',
    description: 'Сбор данных о здоровье пациента',
    category: 'Формы',
    icon: '🏥',
    doc: {
      title: 'Медицинская анкета',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading2', content: 'Данные пациента' },
        { id: gen(), type: 'field', fieldLabel: 'ФИО', fieldOptions: { type: 'text', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Дата рождения', fieldOptions: { type: 'date', required: true } },
        { id: gen(), type: 'field', fieldLabel: 'Группа крови', fieldOptions: { type: 'select', options: ['I (O)', 'II (A)', 'III (B)', 'IV (AB)'] } },
        { id: gen(), type: 'field', fieldLabel: 'Аллергии', fieldOptions: { type: 'textarea', placeholder: 'Перечислите аллергии или напишите "нет"' } },
        { id: gen(), type: 'field', fieldLabel: 'Хронические заболевания', fieldOptions: { type: 'textarea', placeholder: 'Перечислите или напишите "нет"' } },
        { id: gen(), type: 'field', fieldLabel: 'Принимаемые препараты', fieldOptions: { type: 'textarea', placeholder: 'Перечислите или напишите "нет"' } },
        { id: gen(), type: 'signature', content: 'Подпись пациента' },
      ],
    },
  },
  // ─── TABLES ──────────────────────────────────────────────────────────────────
  {
    id: 'budget-table',
    name: 'Таблица бюджета',
    description: 'Планирование и учёт доходов/расходов',
    category: 'Таблицы',
    icon: '💰',
    doc: {
      title: 'Бюджетная таблица',
      blocks: [
        { id: gen(), type: 'heading1', content: 'БЮДЖЕТ НА ____________ 20___ г.', align: 'center' },
        { id: gen(), type: 'heading2', content: 'ДОХОДЫ' },
        { id: gen(), type: 'table', rows: [
          row(cell('Статья доходов', true, '#e8f5e9'), cell('Запланировано', true, '#e8f5e9'), cell('Факт', true, '#e8f5e9'), cell('Отклонение', true, '#e8f5e9')),
          row(cell('Основной доход'), cell(''), cell(''), cell('')),
          row(cell('Дополнительный доход'), cell(''), cell(''), cell('')),
          row(cell('Прочие поступления'), cell(''), cell(''), cell('')),
          row(cell('ИТОГО ДОХОДОВ:', true), cell(''), cell(''), cell('')),
        ], cols: 4 },
        { id: gen(), type: 'heading2', content: 'РАСХОДЫ' },
        { id: gen(), type: 'table', rows: [
          row(cell('Статья расходов', true, '#ffebee'), cell('Запланировано', true, '#ffebee'), cell('Факт', true, '#ffebee'), cell('Отклонение', true, '#ffebee')),
          row(cell('Аренда/ЖКХ'), cell(''), cell(''), cell('')),
          row(cell('Продукты питания'), cell(''), cell(''), cell('')),
          row(cell('Транспорт'), cell(''), cell(''), cell('')),
          row(cell('Коммунальные услуги'), cell(''), cell(''), cell('')),
          row(cell('Развлечения'), cell(''), cell(''), cell('')),
          row(cell('Накопления'), cell(''), cell(''), cell('')),
          row(cell('ИТОГО РАСХОДОВ:', true), cell(''), cell(''), cell('')),
        ], cols: 4 },
        { id: gen(), type: 'table', rows: [
          row(cell('БАЛАНС (Доходы − Расходы):', true, '#fff9c4'), cell('', false, '#fff9c4'), cell('', false, '#fff9c4'), cell('', false, '#fff9c4')),
        ], cols: 4 },
      ],
    },
  },
  {
    id: 'schedule-table',
    name: 'Расписание / График',
    description: 'Еженедельное расписание задач',
    category: 'Таблицы',
    icon: '📅',
    doc: {
      title: 'Расписание',
      blocks: [
        { id: gen(), type: 'heading1', content: 'РАСПИСАНИЕ НА НЕДЕЛЮ', align: 'center' },
        { id: gen(), type: 'table', rows: [
          row(cell('Время', true, '#e3f2fd'), cell('Понедельник', true, '#e3f2fd'), cell('Вторник', true, '#e3f2fd'), cell('Среда', true, '#e3f2fd'), cell('Четверг', true, '#e3f2fd'), cell('Пятница', true, '#e3f2fd'), cell('Суббота', true, '#e3f2fd'), cell('Воскресенье', true, '#e3f2fd')),
          row(cell('08:00–09:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('09:00–10:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('10:00–11:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('11:00–12:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('12:00–13:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('13:00–14:00'), cell('', false, '#fafafa'), cell('', false, '#fafafa'), cell('', false, '#fafafa'), cell('', false, '#fafafa'), cell('', false, '#fafafa'), cell('', false, '#fafafa'), cell('', false, '#fafafa')),
          row(cell('14:00–15:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('15:00–16:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('16:00–17:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('17:00–18:00'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
        ], cols: 8 },
      ],
    },
  },
  {
    id: 'inventory-table',
    name: 'Инвентаризация',
    description: 'Учёт товарно-материальных ценностей',
    category: 'Таблицы',
    icon: '📦',
    doc: {
      title: 'Инвентаризационная ведомость',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ИНВЕНТАРИЗАЦИОННАЯ ВЕДОМОСТЬ', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Дата проведения: ___________   Ответственное лицо: ___________________' },
        { id: gen(), type: 'table', rows: [
          row(cell('№', true, '#e8eaf6'), cell('Наименование', true, '#e8eaf6'), cell('Артикул', true, '#e8eaf6'), cell('Ед.изм', true, '#e8eaf6'), cell('Кол-во (план)', true, '#e8eaf6'), cell('Кол-во (факт)', true, '#e8eaf6'), cell('Цена', true, '#e8eaf6'), cell('Сумма', true, '#e8eaf6'), cell('Примечание', true, '#e8eaf6')),
          row(cell('1'), cell(''), cell(''), cell('шт.'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('2'), cell(''), cell(''), cell('шт.'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('3'), cell(''), cell(''), cell('шт.'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('4'), cell(''), cell(''), cell('шт.'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('5'), cell(''), cell(''), cell('шт.'), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell(''), cell('ИТОГО:', true), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
        ], cols: 9 },
        { id: gen(), type: 'signature', content: 'Комиссия' },
      ],
    },
  },
  {
    id: 'project-plan',
    name: 'Проектный план',
    description: 'Задачи, ответственные и сроки проекта',
    category: 'Таблицы',
    icon: '🗂️',
    doc: {
      title: 'Проектный план',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ПЛАН ПРОЕКТА: ___________________', align: 'center' },
        { id: gen(), type: 'table', rows: [
          row(cell('№', true, '#f3e5f5'), cell('Задача', true, '#f3e5f5'), cell('Ответственный', true, '#f3e5f5'), cell('Начало', true, '#f3e5f5'), cell('Окончание', true, '#f3e5f5'), cell('Статус', true, '#f3e5f5'), cell('%', true, '#f3e5f5'), cell('Примечание', true, '#f3e5f5')),
          row(cell('1'), cell(''), cell(''), cell(''), cell(''), cell('В работе'), cell('0%'), cell('')),
          row(cell('2'), cell(''), cell(''), cell(''), cell(''), cell('Ожидает'), cell('0%'), cell('')),
          row(cell('3'), cell(''), cell(''), cell(''), cell(''), cell('Ожидает'), cell('0%'), cell('')),
          row(cell('4'), cell(''), cell(''), cell(''), cell(''), cell('Ожидает'), cell('0%'), cell('')),
          row(cell('5'), cell(''), cell(''), cell(''), cell(''), cell('Ожидает'), cell('0%'), cell('')),
        ], cols: 8 },
      ],
    },
  },
  {
    id: 'attendance-table',
    name: 'Журнал посещаемости',
    description: 'Учёт явки сотрудников или учеников',
    category: 'Таблицы',
    icon: '✍️',
    doc: {
      title: 'Журнал посещаемости',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ЖУРНАЛ ПОСЕЩАЕМОСТИ', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Месяц: ___________   Группа/Отдел: ___________________' },
        { id: gen(), type: 'table', rows: [
          row(cell('№', true, '#e0f7fa'), cell('ФИО', true, '#e0f7fa'), cell('1', true, '#e0f7fa'), cell('2', true, '#e0f7fa'), cell('3', true, '#e0f7fa'), cell('4', true, '#e0f7fa'), cell('5', true, '#e0f7fa'), cell('...', true, '#e0f7fa'), cell('Итого', true, '#e0f7fa')),
          row(cell('1'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('2'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('3'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('4'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
          row(cell('5'), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell(''), cell('')),
        ], cols: 9 },
      ],
    },
  },
  {
    id: 'price-list',
    name: 'Прайс-лист',
    description: 'Список товаров и услуг с ценами',
    category: 'Таблицы',
    icon: '💲',
    doc: {
      title: 'Прайс-лист',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ПРАЙС-ЛИСТ', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Актуально с: ____________   Срок действия до: ____________', align: 'center' },
        { id: gen(), type: 'heading2', content: 'Категория 1' },
        { id: gen(), type: 'table', rows: [
          row(cell('Наименование', true, '#fff3e0'), cell('Описание', true, '#fff3e0'), cell('Ед.изм.', true, '#fff3e0'), cell('Цена', true, '#fff3e0')),
          row(cell(''), cell(''), cell('шт.'), cell('')),
          row(cell(''), cell(''), cell('шт.'), cell('')),
          row(cell(''), cell(''), cell('шт.'), cell('')),
        ], cols: 4 },
        { id: gen(), type: 'heading2', content: 'Категория 2' },
        { id: gen(), type: 'table', rows: [
          row(cell('Наименование', true, '#fff3e0'), cell('Описание', true, '#fff3e0'), cell('Ед.изм.', true, '#fff3e0'), cell('Цена', true, '#fff3e0')),
          row(cell(''), cell(''), cell('шт.'), cell('')),
          row(cell(''), cell(''), cell('шт.'), cell('')),
        ], cols: 4 },
        { id: gen(), type: 'paragraph', content: '* Цены указаны в рублях, включая НДС 20%' },
      ],
    },
  },
  // ─── OTHER ───────────────────────────────────────────────────────────────────
  {
    id: 'cv',
    name: 'Резюме (CV)',
    description: 'Профессиональное резюме с опытом',
    category: 'Прочее',
    icon: '👤',
    doc: {
      title: 'Резюме',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ИВАНОВ ИВАН ИВАНОВИЧ', align: 'center' },
        { id: gen(), type: 'paragraph', content: '📧 email@example.com  |  📱 +7 (___) ___-__-__  |  📍 г. Москва', align: 'center' },
        { id: gen(), type: 'divider' },
        { id: gen(), type: 'heading2', content: 'ЦЕЛЬ' },
        { id: gen(), type: 'paragraph', content: 'Получение должности _____________________ в компании с возможностью профессионального роста.' },
        { id: gen(), type: 'heading2', content: 'ОПЫТ РАБОТЫ' },
        { id: gen(), type: 'table', rows: [
          row(cell('2020 — наст.вр.', true), cell('Должность, Компания\nОписание обязанностей...')),
          row(cell('2017 — 2020', true), cell('Должность, Компания\nОписание обязанностей...')),
        ], cols: 2 },
        { id: gen(), type: 'heading2', content: 'ОБРАЗОВАНИЕ' },
        { id: gen(), type: 'table', rows: [
          row(cell('2013 — 2017', true), cell('Специальность, Университет')),
        ], cols: 2 },
        { id: gen(), type: 'heading2', content: 'НАВЫКИ' },
        { id: gen(), type: 'list', items: [item('Навык 1'), item('Навык 2'), item('Навык 3')] },
      ],
    },
  },
  {
    id: 'meeting-minutes',
    name: 'Протокол собрания',
    description: 'Официальный протокол совещания',
    category: 'Прочее',
    icon: '🗣️',
    doc: {
      title: 'Протокол собрания',
      blocks: [
        { id: gen(), type: 'heading1', content: 'ПРОТОКОЛ №___', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'общего/рабочего совещания', align: 'center' },
        { id: gen(), type: 'table', rows: [
          row(cell('Дата:', true), cell('________________'), cell('Место:', true), cell('________________')),
          row(cell('Председатель:', true), cell('________________'), cell('Секретарь:', true), cell('________________')),
          row(cell('Присутствовали:', true), cell('________________', false), cell('Приглашены:', true), cell('________________')),
        ], cols: 4 },
        { id: gen(), type: 'heading2', content: 'ПОВЕСТКА ДНЯ:' },
        { id: gen(), type: 'list', items: [item('Вопрос 1'), item('Вопрос 2'), item('Вопрос 3')] },
        { id: gen(), type: 'heading2', content: 'СЛУШАЛИ:' },
        { id: gen(), type: 'paragraph', content: '1. _______________________ — _______________________ (кто, о чём)' },
        { id: gen(), type: 'heading2', content: 'ПОСТАНОВИЛИ:' },
        { id: gen(), type: 'paragraph', content: '1. _______________________. Ответственный: _______. Срок: _______.' },
        { id: gen(), type: 'table', rows: [
          row(cell('Председатель:', true), cell('___________________'), cell('Секретарь:', true), cell('___________________')),
        ], cols: 4 },
      ],
    },
  },
  {
    id: 'checklist',
    name: 'Чек-лист',
    description: 'Список задач с флажками для отметки выполнения',
    category: 'Прочее',
    icon: '☑️',
    doc: {
      title: 'Чек-лист',
      allowFill: true,
      blocks: [
        { id: gen(), type: 'heading1', content: 'ЧЕК-ЛИСТ: ___________________', align: 'center' },
        { id: gen(), type: 'paragraph', content: 'Дата: ___________   Ответственный: ___________________' },
        { id: gen(), type: 'heading2', content: 'Раздел 1' },
        { id: gen(), type: 'checkbox-list', items: [
          { id: gen(), text: 'Задача 1', checked: false },
          { id: gen(), text: 'Задача 2', checked: false },
          { id: gen(), text: 'Задача 3', checked: false },
          { id: gen(), text: 'Задача 4', checked: false },
        ] },
        { id: gen(), type: 'heading2', content: 'Раздел 2' },
        { id: gen(), type: 'checkbox-list', items: [
          { id: gen(), text: 'Задача 1', checked: false },
          { id: gen(), text: 'Задача 2', checked: false },
          { id: gen(), text: 'Задача 3', checked: false },
        ] },
        { id: gen(), type: 'signature', content: 'Подпись проверяющего' },
      ],
    },
  },
];
